version: 0.2
Settings:
  log_transactions: false
Complement:
  seller_name: "Seller"
Msg:
  default:
    prefix: "&9[&3r-Seller&9]> &2"
    error: "&9[&4tr-Seller&9]> &c"
    no_permission: "&4ERROR &9&l> &r&bYou don''t have permission to do that!"
    command_use: "&9[&4tr-Seller&9]> &r&cCommand use: &6$command"
  sellerInteract:
    noShop: "The seller have a problem or is closed"
  sellerInventory:
    buy_price: "Buying price"
    seller_price: "Selling price"
    left_click: "Left click"
    right_click: "Right click"
    shift_click: "Shift+click"
    buy_item: "buy $nbr items"
    leave_the_shop: "Leave the shop"
    next_page_of_shop: "Next page"
    previous_page_of_shop: "Previous page"
    buy_unavailable_inventory: "&3You can't buy this item"
    sell_unavailable_inventory: "&3You can't sell this item"
  transaction:
    success_buy:
      - "&a===================================================="
      - "&3You spend &6$moneySpent for &6$amountItem $itemType"
      - "&3You have now $currentMoney"
      - "&a===================================================="
    failure_buy_no_enough_money:
      - "&a===================================================="
      - "&3You don't have enough, You need&6 $moneyMissing more"
      - "&3for $amount of &6$itemType"
      - "&a===================================================="
    buy_unavailable:
      - "&a===================================================="
      - "&3You can't buy this item"
      - "&a===================================================="
    success_sell:
      - "&a===================================================="
      - "&3You have earned &6$moneySpent for &6$amountItem $itemType"
      - "&3You have now $currentMoney"
      - "&a===================================================="
    failure_sell_no_item:
      - "&a===================================================="
      - "&3You can't sell this item"
      - "&a===================================================="
    sell_unavailable:
      - "&a===================================================="
      - "&3You can't sell this item"
      - "&a===================================================="