version: 0.1
Complement:
  seller_name: "Seller"
Msg:
  default:
    prefix: "&9[&3r-Seller&9]> &2"
    error: "&9[&4tr-Seller&9]> &c"
    no_permission: "&4ERROR &9&l> &r&bYou don''t have permission to do that!"
    command_use: "&9[&4tr-Seller&9]> &r&cCommand use: &6$command"
  sellerInteract:
    noShop: "The seller have a problem or is closed"
  sellerInventory:
    buy_price: "Buying price"
    seller_price: "Selling price"
    left_click: "Left click"
    right_click: "Right click"
    shift_click: "Shift+click"
    buy_item: "buy $nbr items"
    leave_the_shop: "Leave the shop"
    buy_unavailable_inventory: "&3You can't buy this item"
    sell_unavailable_inventory: "&3You can't sell this item"
  transaction:
    success_buy:
      - "&a===================================================="
      - "&3You spend &6$moneySpent for &6$amountItem $itemType"
      - "&3You have now $currentMoney"
      - "&a===================================================="
    failure_buy_no_enough_money:
      - "&a===================================================="
      - "&3You don't have enough, You need&6 $moneyMissing more"
      - "&3for $amount of &6$itemType"
      - "&a===================================================="
    buy_unavailable:
      - "&a===================================================="
      - "&3You can't buy this item"
      - "&a===================================================="
    success_sell:
      - "&a===================================================="
      - "&3You have earned &6$moneySpent for &6$amountItem $itemType"
      - "&3You have now $currentMoney"
      - "&a===================================================="
    failure_sell_no_item:
      - "&a===================================================="
      - "&3You can't sell this item"
      - "&a===================================================="
    sell_unavailable:
      - "&a===================================================="
      - "&3You can't sell this item"
      - "&a===================================================="
      
#exemple shop
version: '0.1'
item:
  name:
    1:
      type: DIAMOND
      data: 0
      DisplayName: "Diamond"
      buy: 200
      sell: 150
      enchantment:
        - ''
        - ''
      lore:
        - ''
        - ''
    2:
      type: STAINED_CLAY
      data: 14
      DisplayName: "red clay"
      buy: 200
      sell: 150
      enchantment:
        - ''
        - ''
      lore:
        - ''
        - ''
    3:
      type: POTION
      data: 0
      DisplayName: "Water bottle"
      buy: 200
      sell: 150
      enchantment:
        - ''
        - ''
      lore:
        - ''
        - ''
    4:
      type: POTION
      data: 16452
      DisplayName: "splash poison potion"
      buy: 200
      sell: 150
      enchantment:
        - ''
        - ''
      lore:
        - ''
        - ''
    5:
      type: WOOD
      data: 0
      DisplayName: "plank of wood"
      buy: 200
      sell: 150
      enchantment:
        - ''
        - ''
      lore:
        - ''
        - ''
    6:
      type: GRASS
      data: 0
      DisplayName: "Grass"
      enchantment:
        - ''
        - ''
      lore:
        - ''
        - ''
    7:
      type: 0
      data: 0
      DisplayName: ""
      enchantment:
        - ''
        - ''
      lore:
        - ''
        - ''
    8:
      type: 0
      data: 0
      DisplayName: ""
      enchantment:
        - ''
        - ''
      lore:
        - ''
        - ''
    9:
      type: 0
      data: 0
      DisplayName: ""
      enchantment:
        - ''
        - ''
      lore:
        - ''
        - ''
        