name: seller
version: 1.0.1
description: Seller du spawn
author: Amosar
depend: [Vault, Citizens]
Loadbefore: [Vault, Citizens]

main: com.trafalcraft.seller.Main

commands:
   seller:
     description: Base command for the vendeur plugin.
     aliases: [vendeur]
     permission: seller.admin
     permission-message: '§4ERROR §9§l> §r§bYou don''t have permission to do that!'
permissions:
  seller.admin: {default: op}